### ISSUE TITLE
particles with NaNs

### ISSUE THREAD

**Issue by DanfengSong** [mxhulab/cryopros#16]
Has anyone tried step 6 in cryosparc version 4.6.0？I got an issue below...
<img width="482" alt="Screenshot 2024-11-01 160338" src="https://github.com/user-attachments/assets/f165a048-efca-4560-a9ab-65655c156d37">

**Comment by zhengdihan** [comment]
Hi, 
In Step 5, could you try using --gen_mode 2? 
The updated cryosparc does not seem compatible with --gen_mode 0.

**Comment by DanfengSong** [comment]
> Hi, In Step 5, could you try using --gen_mode 2? The updated cryosparc does not seem compatible with --gen_mode 0.

Hi,

Thank you for your prompt reply. It works now using --gen_mode 2. Really appreciate it.
